apiVersion: v1
kind: Service
metadata:
  name: {{ include "bearpass-chart.fullname" . }}
  labels:
    {{- include "bearpass-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.sslPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "bearpass-chart.selectorLabels" . | nindent 4 }}

