apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bearpass-chart.fullname" . }}-secrets
  labels:
    {{- include "bearpass-chart.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.env.DATABASE_PASSWORD | b64enc }}
  s3-access-key: {{ .Values.env.S3_ACCESS_KEY | b64enc }}
  s3-secret-key: {{ .Values.env.S3_SECRET_KEY | b64enc }}

